
urls:
  get: "http://localhost:5000/get"
  set: "http://localhost:5000/set"

sites:

  - site: https://motostyle.ua/
    selector: '[itemprop="price"]'
    attribute: content

  - site: https://motakuji.com.ua/
    selector: '[property="product:price:amount"]'
    attribute: content

  - site: https://prom.ua/
    selector: '[data-qaid="product_price"]'
    attribute: data-qaprice

  - site: https://bikermarket.com.ua/
    selector: '[data-qaid="product_price"]'

  - site: https://rsvmoto.com.ua/
    selector: '[itemprop="price"]'
    attribute: content

  - site: https://moto-motion.com.ua/
    selector: '[property="product:price:amount"]'
    attribute: content

  - site: https://www.begemoto.com/
    selector: '[class="old-prices"]'

  - site: https://motoexpress.com.ua/
    selector: '[property="product:price:amount"]'
    attribute: content

  - site: https://www.motokontakt.com.ua/
    selector: '[class="prod-price"]'

  - site: https://motoelit.com.ua/
    selector: '[property="product:price:amount"]'
    attribute: content

  - site: https://motoskarb.com.ua/
    selector: '[data-price-in-default-currency]'
    attribute: data-price-in-default-currency

